package cn.jbolt.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JBolt, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("jb_application", "id", Application.class);
		arp.addMapping("jb_brand", "id", Brand.class);
		arp.addMapping("jb_change_log", "id", ChangeLog.class);
		arp.addMapping("jb_demotable", "id", Demotable.class);
		arp.addMapping("jb_dictionary", "id", Dictionary.class);
		arp.addMapping("jb_dictionary_type", "id", DictionaryType.class);
		arp.addMapping("jb_download_log", "id", DownloadLog.class);
		arp.addMapping("jb_global_config", "id", GlobalConfig.class);
		arp.addMapping("jb_goods", "id", Goods.class);
		arp.addMapping("jb_goods_attr", "id", GoodsAttr.class);
		arp.addMapping("jb_goods_back_category", "id", GoodsBackCategory.class);
		arp.addMapping("jb_goods_element_content", "id", GoodsElementContent.class);
		arp.addMapping("jb_goods_group", "id", GoodsGroup.class);
		arp.addMapping("jb_goods_html_content", "id", GoodsHtmlContent.class);
		arp.addMapping("jb_goods_type", "id", GoodsType.class);
		arp.addMapping("jb_goods_type_brand", "id", GoodsTypeBrand.class);
		arp.addMapping("jb_jbolt_file", "id", JboltFile.class);
		arp.addMapping("jb_jbolt_version", "id", JboltVersion.class);
		arp.addMapping("jb_jbolt_version_file", "id", JboltVersionFile.class);
		arp.addMapping("jb_login_log", "id", LoginLog.class);
		arp.addMapping("jb_mall", "id", Mall.class);
		arp.addMapping("jb_order", "id", Order.class);
		arp.addMapping("jb_order_item", "id", OrderItem.class);
		arp.addMapping("jb_order_shipping", "id", OrderShipping.class);
		arp.addMapping("jb_permission", "id", Permission.class);
		arp.addMapping("jb_remote_login_log", "id", RemoteLoginLog.class);
		arp.addMapping("jb_role", "id", Role.class);
		arp.addMapping("jb_role_permission", "id", RolePermission.class);
		arp.addMapping("jb_shelf", "id", Shelf.class);
		arp.addMapping("jb_shelf_activity", "id", ShelfActivity.class);
		arp.addMapping("jb_shelf_carousel", "id", ShelfCarousel.class);
		arp.addMapping("jb_shelf_element", "id", ShelfElement.class);
		arp.addMapping("jb_shelf_goods_floor", "id", ShelfGoodsFloor.class);
		arp.addMapping("jb_shelf_goods_group", "id", ShelfGoodsGroup.class);
		arp.addMapping("jb_sku", "id", Sku.class);
		arp.addMapping("jb_sku_item", "id", SkuItem.class);
		arp.addMapping("jb_spec", "id", Spec.class);
		arp.addMapping("jb_spec_item", "id", SpecItem.class);
		arp.addMapping("jb_system_log", "id", SystemLog.class);
		arp.addMapping("jb_update_libs", "id", UpdateLibs.class);
		arp.addMapping("jb_user", "id", User.class);
		arp.addMapping("jb_user_config", "id", UserConfig.class);
		arp.addMapping("jb_wechat_article", "id", WechatArticle.class);
		arp.addMapping("jb_wechat_autoreply", "id", WechatAutoreply.class);
		arp.addMapping("jb_wechat_config", "id", WechatConfig.class);
		arp.addMapping("jb_wechat_keywords", "id", WechatKeywords.class);
		arp.addMapping("jb_wechat_media", "id", WechatMedia.class);
		arp.addMapping("jb_wechat_menu", "id", WechatMenu.class);
		arp.addMapping("jb_wechat_mpinfo", "id", WechatMpinfo.class);
		arp.addMapping("jb_wechat_reply_content", "id", WechatReplyContent.class);
		arp.addMapping("jb_wechat_user", "id", WechatUser.class);
	}
}

