package cn.jbolt.common.model;

import cn.jbolt.admin.appdevcenter.ApplicationType;
import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.base.JBoltEnum;
import cn.jbolt.common.model.base.BaseApplication;
import cn.jbolt.common.util.CACHE;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache(keyCache = true,column = "app_id")
public class Application extends BaseApplication<Application> {
	
	public String getTypeName() {
		return JBoltEnum.getTextByValue(ApplicationType.class, getType());
	}
	/**
	 * 额外处理删除其它缓存使用
	 */
	@Override
	public void deleteExtraCache(String action) {
		//不是新增数据的话 才需要删除这个api application的缓存
		if(_actionIsSave(action) == false) {
			CACHE.me.removeApiCallApplication(getAppId());
		}
	}
}
