package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseRemoteLoginLog;

/**
 * 异地登录日志记录
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class RemoteLoginLog extends BaseRemoteLoginLog<RemoteLoginLog> {
}
