package cn.jbolt.common.model;

import cn.jbolt.admin.wechat.mpinfo.WechatMpinfoSubjectType;
import cn.jbolt.admin.wechat.mpinfo.WechatMpinfoType;
import cn.jbolt.base.JBoltEnum;
import cn.jbolt.common.model.base.BaseWechatMpinfo;
import cn.jbolt.common.util.CACHE;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatMpinfo extends BaseWechatMpinfo<WechatMpinfo> {
	/**
	 * 获取账号类型名称
	 * @return
	 */
	public String getTypeName(){
		return JBoltEnum.getTextByValue(WechatMpinfoType.class,getType());
	}
	
	/**
	 * 获取主体类型名称
	 * @return
	 */
	public String getSubjectTypeName(){
		return JBoltEnum.getTextByValue(WechatMpinfoSubjectType.class,getSubjectType());
	}
	
	/**
	 * 获取关联应用名称
	 * @return
	 */
	public String getLinkAppName(){
		return CACHE.me.getApplicationName(getLinkAppId());
	}
	
}
