package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 用户系统样式自定义设置表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserConfig<M extends BaseUserConfig<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 配置名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 配置名
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="配置名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 配置KEY
	 */
	public M setConfigKey(java.lang.String configKey) {
		set("config_key", configKey);
		return (M)this;
	}
	
	/**
	 * 配置KEY
	 */
	@JBoltField(name="configKey" ,columnName="config_key",type="String", remark="配置KEY")
	public java.lang.String getConfigKey() {
		return getStr("config_key");
	}

	/**
	 * 配置值
	 */
	public M setConfigValue(java.lang.String configValue) {
		set("config_value", configValue);
		return (M)this;
	}
	
	/**
	 * 配置值
	 */
	@JBoltField(name="configValue" ,columnName="config_value",type="String", remark="配置值")
	public java.lang.String getConfigValue() {
		return getStr("config_value");
	}

	/**
	 * 用户ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户ID
	 */
	@JBoltField(name="userId" ,columnName="user_id",type="Integer", remark="用户ID")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	@JBoltField(name="updateTime" ,columnName="update_time",type="Date", remark="更新时间")
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 取值类型
	 */
	public M setValueType(java.lang.String valueType) {
		set("value_type", valueType);
		return (M)this;
	}
	
	/**
	 * 取值类型
	 */
	@JBoltField(name="valueType" ,columnName="value_type",type="String", remark="取值类型")
	public java.lang.String getValueType() {
		return getStr("value_type");
	}

}
