package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 全局配置
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGlobalConfig<M extends BaseGlobalConfig<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 配置KEY
	 */
	public M setConfigKey(java.lang.String configKey) {
		set("config_key", configKey);
		return (M)this;
	}
	
	/**
	 * 配置KEY
	 */
	@JBoltField(name="configKey" ,columnName="config_key",type="String", remark="配置KEY")
	public java.lang.String getConfigKey() {
		return getStr("config_key");
	}

	/**
	 * 配置项值
	 */
	public M setConfigValue(java.lang.String configValue) {
		set("config_value", configValue);
		return (M)this;
	}
	
	/**
	 * 配置项值
	 */
	@JBoltField(name="configValue" ,columnName="config_value",type="String", remark="配置项值")
	public java.lang.String getConfigValue() {
		return getStr("config_value");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 创建用户ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 创建用户ID
	 */
	@JBoltField(name="userId" ,columnName="user_id",type="Integer", remark="创建用户ID")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	@JBoltField(name="updateTime" ,columnName="update_time",type="Date", remark="更新时间")
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 更新用户ID
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新用户ID
	 */
	@JBoltField(name="updateUserId" ,columnName="update_user_id",type="Integer", remark="更新用户ID")
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	@JBoltField(name="name" ,columnName="name",type="String", remark="NAME")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 值类型
	 */
	public M setValueType(java.lang.String valueType) {
		set("value_type", valueType);
		return (M)this;
	}
	
	/**
	 * 值类型
	 */
	@JBoltField(name="valueType" ,columnName="value_type",type="String", remark="值类型")
	public java.lang.String getValueType() {
		return getStr("value_type");
	}

}
