package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 用户登录账户表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户名
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	/**
	 * 用户名
	 */
	@JBoltField(name="username" ,columnName="username",type="String", remark="用户名")
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 密码
	 */
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	/**
	 * 密码
	 */
	@JBoltField(name="password" ,columnName="password",type="String", remark="密码")
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 姓名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 姓名
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="姓名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 头像
	 */
	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	/**
	 * 头像
	 */
	@JBoltField(name="avatar" ,columnName="avatar",type="String", remark="头像")
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 记录创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 记录创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="记录创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 手机号
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 手机号
	 */
	@JBoltField(name="phone" ,columnName="phone",type="String", remark="手机号")
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 启用
	 */
	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	/**
	 * 启用
	 */
	@JBoltField(name="enable" ,columnName="enable",type="Boolean", remark="启用")
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

	/**
	 * 性别
	 */
	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	/**
	 * 性别
	 */
	@JBoltField(name="sex" ,columnName="sex",type="Integer", remark="性别")
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	/**
	 * 拼音码
	 */
	public M setPinyin(java.lang.String pinyin) {
		set("pinyin", pinyin);
		return (M)this;
	}
	
	/**
	 * 拼音码
	 */
	@JBoltField(name="pinyin" ,columnName="pinyin",type="String", remark="拼音码")
	public java.lang.String getPinyin() {
		return getStr("pinyin");
	}

	/**
	 * 角色 一对多
	 */
	public M setRoles(java.lang.String roles) {
		set("roles", roles);
		return (M)this;
	}
	
	/**
	 * 角色 一对多
	 */
	@JBoltField(name="roles" ,columnName="roles",type="String", remark="角色 一对多")
	public java.lang.String getRoles() {
		return getStr("roles");
	}

	/**
	 * 是否系统超级管理员
	 */
	public M setIsSystemAdmin(java.lang.Boolean isSystemAdmin) {
		set("is_system_admin", isSystemAdmin);
		return (M)this;
	}
	
	/**
	 * 是否系统超级管理员
	 */
	@JBoltField(name="isSystemAdmin" ,columnName="is_system_admin",type="Boolean", remark="是否系统超级管理员")
	public java.lang.Boolean getIsSystemAdmin() {
		return getBoolean("is_system_admin");
	}

	/**
	 * 创建人
	 */
	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建人
	 */
	@JBoltField(name="createUserId" ,columnName="create_user_id",type="Integer", remark="创建人")
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	/**
	 * 密码盐值
	 */
	public M setPwdSalt(java.lang.String pwdSalt) {
		set("pwd_salt", pwdSalt);
		return (M)this;
	}
	
	/**
	 * 密码盐值
	 */
	@JBoltField(name="pwdSalt" ,columnName="pwd_salt",type="String", remark="密码盐值")
	public java.lang.String getPwdSalt() {
		return getStr("pwd_salt");
	}

	/**
	 * 最后登录IP
	 */
	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}
	
	/**
	 * 最后登录IP
	 */
	@JBoltField(name="loginIp" ,columnName="login_ip",type="String", remark="最后登录IP")
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	/**
	 * 最后登录时间
	 */
	public M setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
		return (M)this;
	}
	
	/**
	 * 最后登录时间
	 */
	@JBoltField(name="loginTime" ,columnName="login_time",type="Date", remark="最后登录时间")
	public java.util.Date getLoginTime() {
		return getDate("login_time");
	}

	/**
	 * 最后登录城市
	 */
	public M setLoginCity(java.lang.String loginCity) {
		set("login_city", loginCity);
		return (M)this;
	}
	
	/**
	 * 最后登录城市
	 */
	@JBoltField(name="loginCity" ,columnName="login_city",type="String", remark="最后登录城市")
	public java.lang.String getLoginCity() {
		return getStr("login_city");
	}

	/**
	 * 最后登录省份
	 */
	public M setLoginProvince(java.lang.String loginProvince) {
		set("login_province", loginProvince);
		return (M)this;
	}
	
	/**
	 * 最后登录省份
	 */
	@JBoltField(name="loginProvince" ,columnName="login_province",type="String", remark="最后登录省份")
	public java.lang.String getLoginProvince() {
		return getStr("login_province");
	}

	/**
	 * 是否异地登录
	 */
	public M setIsRemoteLogin(java.lang.Boolean isRemoteLogin) {
		set("is_remote_login", isRemoteLogin);
		return (M)this;
	}
	
	/**
	 * 是否异地登录
	 */
	@JBoltField(name="isRemoteLogin" ,columnName="is_remote_login",type="Boolean", remark="是否异地登录")
	public java.lang.Boolean getIsRemoteLogin() {
		return getBoolean("is_remote_login");
	}

}
