package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 微信公众号自动回复规则
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatAutoreply<M extends BaseWechatAutoreply<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	@JBoltField(name="mpId" ,columnName="mp_id",type="Integer", remark="微信 ID")
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	/**
	 * 类型 关注回复 无内容时回复 关键词回复
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型 关注回复 无内容时回复 关键词回复
	 */
	@JBoltField(name="type" ,columnName="type",type="Integer", remark="类型 关注回复 无内容时回复 关键词回复")
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 规则名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 规则名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="规则名称")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 回复类型 全部还是随机一条
	 */
	public M setReplyType(java.lang.Integer replyType) {
		set("reply_type", replyType);
		return (M)this;
	}
	
	/**
	 * 回复类型 全部还是随机一条
	 */
	@JBoltField(name="replyType" ,columnName="reply_type",type="Integer", remark="回复类型 全部还是随机一条")
	public java.lang.Integer getReplyType() {
		return getInt("reply_type");
	}

	/**
	 * 记录创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 记录创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="记录创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 用户 ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户 ID
	 */
	@JBoltField(name="userId" ,columnName="user_id",type="Integer", remark="用户 ID")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	@JBoltField(name="enable" ,columnName="enable",type="Boolean", remark="ENABLE")
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

}
