package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 微信公众平台素材库同步管理
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatMedia<M extends BaseWechatMedia<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 标题
	 */
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	/**
	 * 标题
	 */
	@JBoltField(name="title" ,columnName="title",type="String", remark="标题")
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 描述
	 */
	public M setDigest(java.lang.String digest) {
		set("digest", digest);
		return (M)this;
	}
	
	/**
	 * 描述
	 */
	@JBoltField(name="digest" ,columnName="digest",type="String", remark="描述")
	public java.lang.String getDigest() {
		return getStr("digest");
	}

	/**
	 * 类型 image video voice news
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型 image video voice news
	 */
	@JBoltField(name="type" ,columnName="type",type="String", remark="类型 image video voice news")
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	@JBoltField(name="mpId" ,columnName="mp_id",type="Integer", remark="微信 ID")
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	/**
	 * 微信素材ID
	 */
	public M setMediaId(java.lang.String mediaId) {
		set("media_id", mediaId);
		return (M)this;
	}
	
	/**
	 * 微信素材ID
	 */
	@JBoltField(name="mediaId" ,columnName="media_id",type="String", remark="微信素材ID")
	public java.lang.String getMediaId() {
		return getStr("media_id");
	}

	/**
	 * 封面图ID
	 */
	public M setThumbMediaId(java.lang.String thumbMediaId) {
		set("thumb_media_id", thumbMediaId);
		return (M)this;
	}
	
	/**
	 * 封面图ID
	 */
	@JBoltField(name="thumbMediaId" ,columnName="thumb_media_id",type="String", remark="封面图ID")
	public java.lang.String getThumbMediaId() {
		return getStr("thumb_media_id");
	}

	/**
	 * 原文地址
	 */
	public M setContentSourceUrl(java.lang.String contentSourceUrl) {
		set("content_source_url", contentSourceUrl);
		return (M)this;
	}
	
	/**
	 * 原文地址
	 */
	@JBoltField(name="contentSourceUrl" ,columnName="content_source_url",type="String", remark="原文地址")
	public java.lang.String getContentSourceUrl() {
		return getStr("content_source_url");
	}

	/**
	 * 访问地址
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 访问地址
	 */
	@JBoltField(name="url" ,columnName="url",type="String", remark="访问地址")
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 图文作者
	 */
	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	/**
	 * 图文作者
	 */
	@JBoltField(name="author" ,columnName="author",type="String", remark="图文作者")
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	@JBoltField(name="updateTime" ,columnName="update_time",type="Date", remark="更新时间")
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 存服务器URL
	 */
	public M setServerUrl(java.lang.String serverUrl) {
		set("server_url", serverUrl);
		return (M)this;
	}
	
	/**
	 * 存服务器URL
	 */
	@JBoltField(name="serverUrl" ,columnName="server_url",type="String", remark="存服务器URL")
	public java.lang.String getServerUrl() {
		return getStr("server_url");
	}

}
