package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 商品自定义属性
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsAttr<M extends BaseGoodsAttr<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 属性名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 属性名
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="属性名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 属性值
	 */
	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	/**
	 * 属性值
	 */
	@JBoltField(name="value" ,columnName="value",type="String", remark="属性值")
	public java.lang.String getValue() {
		return getStr("value");
	}

	/**
	 * 商品ID
	 */
	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品ID
	 */
	@JBoltField(name="goodsId" ,columnName="goods_id",type="Integer", remark="商品ID")
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

}
