package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 角色功能列表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 角色ID
	 */
	public M setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}
	
	/**
	 * 角色ID
	 */
	@JBoltField(name="roleId" ,columnName="role_id",type="Integer", remark="角色ID")
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	/**
	 * 权限ID
	 */
	public M setPermissionId(java.lang.Integer permissionId) {
		set("permission_id", permissionId);
		return (M)this;
	}
	
	/**
	 * 权限ID
	 */
	@JBoltField(name="permissionId" ,columnName="permission_id",type="Integer", remark="权限ID")
	public java.lang.Integer getPermissionId() {
		return getInt("permission_id");
	}

}
