package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 商品分组
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsGroup<M extends BaseGoodsGroup<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="名称")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.String sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="String", remark="排序")
	public java.lang.String getSortRank() {
		return getStr("sort_rank");
	}

	/**
	 * 图标
	 */
	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	/**
	 * 图标
	 */
	@JBoltField(name="icon" ,columnName="icon",type="String", remark="图标")
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 商品数量
	 */
	public M setGoodsCount(java.lang.Integer goodsCount) {
		set("goods_count", goodsCount);
		return (M)this;
	}
	
	/**
	 * 商品数量
	 */
	@JBoltField(name="goodsCount" ,columnName="goods_count",type="Integer", remark="商品数量")
	public java.lang.Integer getGoodsCount() {
		return getInt("goods_count");
	}

	/**
	 * 是否启用
	 */
	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	/**
	 * 是否启用
	 */
	@JBoltField(name="enable" ,columnName="enable",type="Boolean", remark="是否启用")
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

}
