package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 下载log
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDownloadLog<M extends BaseDownloadLog<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIpaddress(java.lang.String ipaddress) {
		set("ipaddress", ipaddress);
		return (M)this;
	}
	
	@JBoltField(name="ipaddress" ,columnName="ipaddress",type="String", remark="IPADDRESS")
	public java.lang.String getIpaddress() {
		return getStr("ipaddress");
	}

	/**
	 * 下载类型
	 */
	public M setDownloadType(java.lang.Integer downloadType) {
		set("download_type", downloadType);
		return (M)this;
	}
	
	/**
	 * 下载类型
	 */
	@JBoltField(name="downloadType" ,columnName="download_type",type="Integer", remark="下载类型")
	public java.lang.Integer getDownloadType() {
		return getInt("download_type");
	}

	/**
	 * 下载时间
	 */
	public M setDownloadTime(java.util.Date downloadTime) {
		set("download_time", downloadTime);
		return (M)this;
	}
	
	/**
	 * 下载时间
	 */
	@JBoltField(name="downloadTime" ,columnName="download_time",type="Date", remark="下载时间")
	public java.util.Date getDownloadTime() {
		return getDate("download_time");
	}

}
