package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 角色表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRole<M extends BaseRole<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="名称")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 父级角色ID
	 */
	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	/**
	 * 父级角色ID
	 */
	@JBoltField(name="pid" ,columnName="pid",type="Integer", remark="父级角色ID")
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

}
