package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 字典表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDictionary<M extends BaseDictionary<M>> extends JBoltBaseModel<M>{

	/**
	 * 字典ID主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 字典ID主键
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="字典ID主键")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="名称")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 字典类型ID
	 */
	public M setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
		return (M)this;
	}
	
	/**
	 * 字典类型ID
	 */
	@JBoltField(name="typeId" ,columnName="type_id",type="Integer", remark="字典类型ID")
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	/**
	 * 父类ID
	 */
	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	/**
	 * 父类ID
	 */
	@JBoltField(name="pid" ,columnName="pid",type="Integer", remark="父类ID")
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="排序")
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 编号编码
	 */
	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}
	
	/**
	 * 编号编码
	 */
	@JBoltField(name="sn" ,columnName="sn",type="String", remark="编号编码")
	public java.lang.String getSn() {
		return getStr("sn");
	}

	/**
	 * 字典类型KEY
	 */
	public M setTypeKey(java.lang.String typeKey) {
		set("type_key", typeKey);
		return (M)this;
	}
	
	/**
	 * 字典类型KEY
	 */
	@JBoltField(name="typeKey" ,columnName="type_key",type="String", remark="字典类型KEY")
	public java.lang.String getTypeKey() {
		return getStr("type_key");
	}

}
