package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 商城表一条数据代表一个商城
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMall<M extends BaseMall<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商城名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 商城名称
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="商城名称")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 创建人
	 */
	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建人
	 */
	@JBoltField(name="createUserId" ,columnName="create_user_id",type="Integer", remark="创建人")
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	@JBoltField(name="updateTime" ,columnName="update_time",type="Date", remark="更新时间")
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 更新操作人
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新操作人
	 */
	@JBoltField(name="updateUserId" ,columnName="update_user_id",type="Integer", remark="更新操作人")
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	/**
	 * 状态 1筹备中 2 已上线 3 关闭
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 状态 1筹备中 2 已上线 3 关闭
	 */
	@JBoltField(name="state" ,columnName="state",type="Integer", remark="状态 1筹备中 2 已上线 3 关闭")
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 负责人
	 */
	public M setLeaderId(java.lang.Integer leaderId) {
		set("leader_id", leaderId);
		return (M)this;
	}
	
	/**
	 * 负责人
	 */
	@JBoltField(name="leaderId" ,columnName="leader_id",type="Integer", remark="负责人")
	public java.lang.Integer getLeaderId() {
		return getInt("leader_id");
	}

	/**
	 * 首次上线发布时间
	 */
	public M setFirstPublishTime(java.util.Date firstPublishTime) {
		set("first_publish_time", firstPublishTime);
		return (M)this;
	}
	
	/**
	 * 首次上线发布时间
	 */
	@JBoltField(name="firstPublishTime" ,columnName="first_publish_time",type="Date", remark="首次上线发布时间")
	public java.util.Date getFirstPublishTime() {
		return getDate("first_publish_time");
	}

	/**
	 * 最近一次上线发布操作时间
	 */
	public M setLastPublishTime(java.util.Date lastPublishTime) {
		set("last_publish_time", lastPublishTime);
		return (M)this;
	}
	
	/**
	 * 最近一次上线发布操作时间
	 */
	@JBoltField(name="lastPublishTime" ,columnName="last_publish_time",type="Date", remark="最近一次上线发布操作时间")
	public java.util.Date getLastPublishTime() {
		return getDate("last_publish_time");
	}

	/**
	 * 首次关闭时间
	 */
	public M setFirstCloseTime(java.util.Date firstCloseTime) {
		set("first_close_time", firstCloseTime);
		return (M)this;
	}
	
	/**
	 * 首次关闭时间
	 */
	@JBoltField(name="firstCloseTime" ,columnName="first_close_time",type="Date", remark="首次关闭时间")
	public java.util.Date getFirstCloseTime() {
		return getDate("first_close_time");
	}

	/**
	 * 最近一次关闭时间
	 */
	public M setLastCloseTime(java.util.Date lastCloseTime) {
		set("last_close_time", lastCloseTime);
		return (M)this;
	}
	
	/**
	 * 最近一次关闭时间
	 */
	@JBoltField(name="lastCloseTime" ,columnName="last_close_time",type="Date", remark="最近一次关闭时间")
	public java.util.Date getLastCloseTime() {
		return getDate("last_close_time");
	}

	/**
	 * 首次发布人
	 */
	public M setFirstPublishUserId(java.lang.Integer firstPublishUserId) {
		set("first_publish_user_id", firstPublishUserId);
		return (M)this;
	}
	
	/**
	 * 首次发布人
	 */
	@JBoltField(name="firstPublishUserId" ,columnName="first_publish_user_id",type="Integer", remark="首次发布人")
	public java.lang.Integer getFirstPublishUserId() {
		return getInt("first_publish_user_id");
	}

	/**
	 * 最近一次发布人
	 */
	public M setLastPublishUserId(java.lang.Integer lastPublishUserId) {
		set("last_publish_user_id", lastPublishUserId);
		return (M)this;
	}
	
	/**
	 * 最近一次发布人
	 */
	@JBoltField(name="lastPublishUserId" ,columnName="last_publish_user_id",type="Integer", remark="最近一次发布人")
	public java.lang.Integer getLastPublishUserId() {
		return getInt("last_publish_user_id");
	}

	/**
	 * 首次关闭商城操作人
	 */
	public M setFirstCloseUserId(java.lang.Integer firstCloseUserId) {
		set("first_close_user_id", firstCloseUserId);
		return (M)this;
	}
	
	/**
	 * 首次关闭商城操作人
	 */
	@JBoltField(name="firstCloseUserId" ,columnName="first_close_user_id",type="Integer", remark="首次关闭商城操作人")
	public java.lang.Integer getFirstCloseUserId() {
		return getInt("first_close_user_id");
	}

	/**
	 * 最近一次关闭操作人
	 */
	public M setLastCloseUserId(java.lang.Integer lastCloseUserId) {
		set("last_close_user_id", lastCloseUserId);
		return (M)this;
	}
	
	/**
	 * 最近一次关闭操作人
	 */
	@JBoltField(name="lastCloseUserId" ,columnName="last_close_user_id",type="Integer", remark="最近一次关闭操作人")
	public java.lang.Integer getLastCloseUserId() {
		return getInt("last_close_user_id");
	}

}
