package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 自动回复内容
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatReplyContent<M extends BaseWechatReplyContent<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类型 图文 文字 图片 音频 视频
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型 图文 文字 图片 音频 视频
	 */
	@JBoltField(name="type" ,columnName="type",type="String", remark="类型 图文 文字 图片 音频 视频")
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	@JBoltField(name="title" ,columnName="title",type="String", remark="TITLE")
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	@JBoltField(name="content" ,columnName="content",type="String", remark="CONTENT")
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPoster(java.lang.String poster) {
		set("poster", poster);
		return (M)this;
	}
	
	@JBoltField(name="poster" ,columnName="poster",type="String", remark="POSTER")
	public java.lang.String getPoster() {
		return getStr("poster");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	@JBoltField(name="url" ,columnName="url",type="String", remark="URL")
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 回复规则ID
	 */
	public M setAutoReplyId(java.lang.Integer autoReplyId) {
		set("auto_reply_id", autoReplyId);
		return (M)this;
	}
	
	/**
	 * 回复规则ID
	 */
	@JBoltField(name="autoReplyId" ,columnName="auto_reply_id",type="Integer", remark="回复规则ID")
	public java.lang.Integer getAutoReplyId() {
		return getInt("auto_reply_id");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 用户 ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户 ID
	 */
	@JBoltField(name="userId" ,columnName="user_id",type="Integer", remark="用户 ID")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 关联数据
	 */
	public M setMediaId(java.lang.String mediaId) {
		set("media_id", mediaId);
		return (M)this;
	}
	
	/**
	 * 关联数据
	 */
	@JBoltField(name="mediaId" ,columnName="media_id",type="String", remark="关联数据")
	public java.lang.String getMediaId() {
		return getStr("media_id");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	@JBoltField(name="mpId" ,columnName="mp_id",type="Integer", remark="微信 ID")
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="排序")
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	@JBoltField(name="enable" ,columnName="enable",type="Boolean", remark="ENABLE")
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

}
