package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 商城订单
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单编号
	 */
	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	/**
	 * 订单编号
	 */
	@JBoltField(name="orderNo" ,columnName="order_no",type="String", remark="订单编号")
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 下单时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 下单时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="下单时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 买家ID
	 */
	public M setBuyerId(java.lang.Integer buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}
	
	/**
	 * 买家ID
	 */
	@JBoltField(name="buyerId" ,columnName="buyer_id",type="Integer", remark="买家ID")
	public java.lang.Integer getBuyerId() {
		return getInt("buyer_id");
	}

	/**
	 * 冗余买家名字
	 */
	public M setBuyerName(java.lang.String buyerName) {
		set("buyer_name", buyerName);
		return (M)this;
	}
	
	/**
	 * 冗余买家名字
	 */
	@JBoltField(name="buyerName" ,columnName="buyer_name",type="String", remark="冗余买家名字")
	public java.lang.String getBuyerName() {
		return getStr("buyer_name");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	@JBoltField(name="updateTime" ,columnName="update_time",type="Date", remark="更新时间")
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 付款时间
	 */
	public M setPaymentTime(java.util.Date paymentTime) {
		set("payment_time", paymentTime);
		return (M)this;
	}
	
	/**
	 * 付款时间
	 */
	@JBoltField(name="paymentTime" ,columnName="payment_time",type="Date", remark="付款时间")
	public java.util.Date getPaymentTime() {
		return getDate("payment_time");
	}

	/**
	 * 发货时间
	 */
	public M setConsignTime(java.util.Date consignTime) {
		set("consign_time", consignTime);
		return (M)this;
	}
	
	/**
	 * 发货时间
	 */
	@JBoltField(name="consignTime" ,columnName="consign_time",type="Date", remark="发货时间")
	public java.util.Date getConsignTime() {
		return getDate("consign_time");
	}

	/**
	 * 交易完成时间
	 */
	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}
	
	/**
	 * 交易完成时间
	 */
	@JBoltField(name="finishTime" ,columnName="finish_time",type="Date", remark="交易完成时间")
	public java.util.Date getFinishTime() {
		return getDate("finish_time");
	}

	/**
	 * 订单关闭时间
	 */
	public M setCloseTime(java.util.Date closeTime) {
		set("close_time", closeTime);
		return (M)this;
	}
	
	/**
	 * 订单关闭时间
	 */
	@JBoltField(name="closeTime" ,columnName="close_time",type="Date", remark="订单关闭时间")
	public java.util.Date getCloseTime() {
		return getDate("close_time");
	}

	/**
	 * 卖家留言
	 */
	public M setBuyerMessage(java.lang.String buyerMessage) {
		set("buyer_message", buyerMessage);
		return (M)this;
	}
	
	/**
	 * 卖家留言
	 */
	@JBoltField(name="buyerMessage" ,columnName="buyer_message",type="String", remark="卖家留言")
	public java.lang.String getBuyerMessage() {
		return getStr("buyer_message");
	}

	/**
	 * 买家是否已经评价
	 */
	public M setBuyerRate(java.lang.Boolean buyerRate) {
		set("buyer_rate", buyerRate);
		return (M)this;
	}
	
	/**
	 * 买家是否已经评价
	 */
	@JBoltField(name="buyerRate" ,columnName="buyer_rate",type="Boolean", remark="买家是否已经评价")
	public java.lang.Boolean getBuyerRate() {
		return getBoolean("buyer_rate");
	}

	/**
	 * 订单状态 待付款 已付款 已发货 订单完成 订单关闭
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 订单状态 待付款 已付款 已发货 订单完成 订单关闭
	 */
	@JBoltField(name="state" ,columnName="state",type="Integer", remark="订单状态 待付款 已付款 已发货 订单完成 订单关闭")
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 总额
	 */
	public M setGoodsAmount(java.math.BigDecimal goodsAmount) {
		set("goods_amount", goodsAmount);
		return (M)this;
	}
	
	/**
	 * 总额
	 */
	@JBoltField(name="goodsAmount" ,columnName="goods_amount",type="BigDecimal", remark="总额")
	public java.math.BigDecimal getGoodsAmount() {
		return get("goods_amount");
	}

	/**
	 * 运费
	 */
	public M setPostFee(java.math.BigDecimal postFee) {
		set("post_fee", postFee);
		return (M)this;
	}
	
	/**
	 * 运费
	 */
	@JBoltField(name="postFee" ,columnName="post_fee",type="BigDecimal", remark="运费")
	public java.math.BigDecimal getPostFee() {
		return get("post_fee");
	}

	/**
	 * 应付总额
	 */
	public M setPaymentAmount(java.math.BigDecimal paymentAmount) {
		set("payment_amount", paymentAmount);
		return (M)this;
	}
	
	/**
	 * 应付总额
	 */
	@JBoltField(name="paymentAmount" ,columnName="payment_amount",type="BigDecimal", remark="应付总额")
	public java.math.BigDecimal getPaymentAmount() {
		return get("payment_amount");
	}

	/**
	 * 支付类型 在线支付 货到付款
	 */
	public M setPaymentType(java.lang.Integer paymentType) {
		set("payment_type", paymentType);
		return (M)this;
	}
	
	/**
	 * 支付类型 在线支付 货到付款
	 */
	@JBoltField(name="paymentType" ,columnName="payment_type",type="Integer", remark="支付类型 在线支付 货到付款")
	public java.lang.Integer getPaymentType() {
		return getInt("payment_type");
	}

	/**
	 * 在线支付选择了谁
	 */
	public M setOnlinePaymentType(java.lang.Integer onlinePaymentType) {
		set("online_payment_type", onlinePaymentType);
		return (M)this;
	}
	
	/**
	 * 在线支付选择了谁
	 */
	@JBoltField(name="onlinePaymentType" ,columnName="online_payment_type",type="Integer", remark="在线支付选择了谁")
	public java.lang.Integer getOnlinePaymentType() {
		return getInt("online_payment_type");
	}

	/**
	 * 通过什么方式关闭 后台管理 or 客户自身
	 */
	public M setCloseType(java.lang.Integer closeType) {
		set("close_type", closeType);
		return (M)this;
	}
	
	/**
	 * 通过什么方式关闭 后台管理 or 客户自身
	 */
	@JBoltField(name="closeType" ,columnName="close_type",type="Integer", remark="通过什么方式关闭 后台管理 or 客户自身")
	public java.lang.Integer getCloseType() {
		return getInt("close_type");
	}

	/**
	 * 关闭订单用户ID
	 */
	public M setCloseUesrId(java.lang.Integer closeUesrId) {
		set("close_uesr_id", closeUesrId);
		return (M)this;
	}
	
	/**
	 * 关闭订单用户ID
	 */
	@JBoltField(name="closeUesrId" ,columnName="close_uesr_id",type="Integer", remark="关闭订单用户ID")
	public java.lang.Integer getCloseUesrId() {
		return getInt("close_uesr_id");
	}

}
