package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDemotable<M extends BaseDemotable<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * demo日期
	 */
	public M setDemoDate(java.util.Date demoDate) {
		set("demo_date", demoDate);
		return (M)this;
	}
	
	/**
	 * demo日期
	 */
	@JBoltField(name="demoDate" ,columnName="demo_date",type="Date", remark="demo日期")
	public java.util.Date getDemoDate() {
		return getDate("demo_date");
	}

	/**
	 * demo时间
	 */
	public M setDemoTime(java.sql.Time demoTime) {
		set("demo_time", demoTime);
		return (M)this;
	}
	
	/**
	 * demo时间
	 */
	@JBoltField(name="demoTime" ,columnName="demo_time",type="Time", remark="demo时间")
	public java.sql.Time getDemoTime() {
		return getTime("demo_time");
	}

	/**
	 * demo日期与时间
	 */
	public M setDemoDateTime(java.util.Date demoDateTime) {
		set("demo_date_time", demoDateTime);
		return (M)this;
	}
	
	/**
	 * demo日期与时间
	 */
	@JBoltField(name="demoDateTime" ,columnName="demo_date_time",type="Date", remark="demo日期与时间")
	public java.util.Date getDemoDateTime() {
		return getDate("demo_date_time");
	}

	/**
	 * demo周
	 */
	public M setDemoWeek(java.lang.String demoWeek) {
		set("demo_week", demoWeek);
		return (M)this;
	}
	
	/**
	 * demo周
	 */
	@JBoltField(name="demoWeek" ,columnName="demo_week",type="String", remark="demo周")
	public java.lang.String getDemoWeek() {
		return getStr("demo_week");
	}

	/**
	 * demo月
	 */
	public M setDemoMonth(java.lang.String demoMonth) {
		set("demo_month", demoMonth);
		return (M)this;
	}
	
	/**
	 * demo月
	 */
	@JBoltField(name="demoMonth" ,columnName="demo_month",type="String", remark="demo月")
	public java.lang.String getDemoMonth() {
		return getStr("demo_month");
	}

	/**
	 * demo纯时间
	 */
	public M setTime(java.sql.Time time) {
		set("time", time);
		return (M)this;
	}
	
	/**
	 * demo纯时间
	 */
	@JBoltField(name="time" ,columnName="time",type="Time", remark="demo纯时间")
	public java.sql.Time getTime() {
		return getTime("time");
	}

	/**
	 * 启用
	 */
	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	/**
	 * 启用
	 */
	@JBoltField(name="enable" ,columnName="enable",type="Boolean", remark="启用")
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

	/**
	 * 父级ID
	 */
	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	/**
	 * 父级ID
	 */
	@JBoltField(name="pid" ,columnName="pid",type="Integer", remark="父级ID")
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 序号
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="序号")
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 姓名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 姓名
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="姓名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 年龄
	 */
	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	/**
	 * 年龄
	 */
	@JBoltField(name="age" ,columnName="age",type="Integer", remark="年龄")
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	/**
	 * 简介
	 */
	public M setBreifInfo(java.lang.String breifInfo) {
		set("breif_info", breifInfo);
		return (M)this;
	}
	
	/**
	 * 简介
	 */
	@JBoltField(name="breifInfo" ,columnName="breif_info",type="String", remark="简介")
	public java.lang.String getBreifInfo() {
		return getStr("breif_info");
	}

	/**
	 * 是否为管理
	 */
	public M setIsSystemAdmin(java.lang.Boolean isSystemAdmin) {
		set("is_system_admin", isSystemAdmin);
		return (M)this;
	}
	
	/**
	 * 是否为管理
	 */
	@JBoltField(name="isSystemAdmin" ,columnName="is_system_admin",type="Boolean", remark="是否为管理")
	public java.lang.Boolean getIsSystemAdmin() {
		return getBoolean("is_system_admin");
	}

}
