package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 规格选项表
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSpecItem<M extends BaseSpecItem<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 选项名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 选项名
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="选项名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 所属规格
	 */
	public M setSpecId(java.lang.Integer specId) {
		set("spec_id", specId);
		return (M)this;
	}
	
	/**
	 * 所属规格
	 */
	@JBoltField(name="specId" ,columnName="spec_id",type="Integer", remark="所属规格")
	public java.lang.Integer getSpecId() {
		return getInt("spec_id");
	}

}
