package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * function定义
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePermission<M extends BasePermission<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	@JBoltField(name="title" ,columnName="title",type="String", remark="TITLE")
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	@JBoltField(name="pid" ,columnName="pid",type="Integer", remark="PID")
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 地址
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 地址
	 */
	@JBoltField(name="url" ,columnName="url",type="String", remark="地址")
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 图标
	 */
	public M setIcons(java.lang.String icons) {
		set("icons", icons);
		return (M)this;
	}
	
	/**
	 * 图标
	 */
	@JBoltField(name="icons" ,columnName="icons",type="String", remark="图标")
	public java.lang.String getIcons() {
		return getStr("icons");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="排序")
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 层级
	 */
	public M setPermissionLevel(java.lang.Integer permissionLevel) {
		set("permission_level", permissionLevel);
		return (M)this;
	}
	
	/**
	 * 层级
	 */
	@JBoltField(name="permissionLevel" ,columnName="permission_level",type="Integer", remark="层级")
	public java.lang.Integer getPermissionLevel() {
		return getInt("permission_level");
	}

	/**
	 * 权限资源KEY
	 */
	public M setPermissionKey(java.lang.String permissionKey) {
		set("permission_key", permissionKey);
		return (M)this;
	}
	
	/**
	 * 权限资源KEY
	 */
	@JBoltField(name="permissionKey" ,columnName="permission_key",type="String", remark="权限资源KEY")
	public java.lang.String getPermissionKey() {
		return getStr("permission_key");
	}

	/**
	 * 是否是菜单
	 */
	public M setIsMenu(java.lang.Boolean isMenu) {
		set("is_menu", isMenu);
		return (M)this;
	}
	
	/**
	 * 是否是菜单
	 */
	@JBoltField(name="isMenu" ,columnName="is_menu",type="Boolean", remark="是否是菜单")
	public java.lang.Boolean getIsMenu() {
		return getBoolean("is_menu");
	}

	/**
	 * 是否新窗口打开
	 */
	public M setIsTargetBlank(java.lang.Boolean isTargetBlank) {
		set("is_target_blank", isTargetBlank);
		return (M)this;
	}
	
	/**
	 * 是否新窗口打开
	 */
	@JBoltField(name="isTargetBlank" ,columnName="is_target_blank",type="Boolean", remark="是否新窗口打开")
	public java.lang.Boolean getIsTargetBlank() {
		return getBoolean("is_target_blank");
	}

	/**
	 * 是否系统超级管理员默认拥有的权限
	 */
	public M setIsSystemAdminDefault(java.lang.Boolean isSystemAdminDefault) {
		set("is_system_admin_default", isSystemAdminDefault);
		return (M)this;
	}
	
	/**
	 * 是否系统超级管理员默认拥有的权限
	 */
	@JBoltField(name="isSystemAdminDefault" ,columnName="is_system_admin_default",type="Boolean", remark="是否系统超级管理员默认拥有的权限")
	public java.lang.Boolean getIsSystemAdminDefault() {
		return getBoolean("is_system_admin_default");
	}

	/**
	 * 打开类型 1 默认 2 iframe 3 dialog
	 */
	public M setOpenType(java.lang.Integer openType) {
		set("open_type", openType);
		return (M)this;
	}
	
	/**
	 * 打开类型 1 默认 2 iframe 3 dialog
	 */
	@JBoltField(name="openType" ,columnName="open_type",type="Integer", remark="打开类型 1 默认 2 iframe 3 dialog")
	public java.lang.Integer getOpenType() {
		return getInt("open_type");
	}

	/**
	 * 组件属性json
	 */
	public M setOpenOption(java.lang.String openOption) {
		set("open_option", openOption);
		return (M)this;
	}
	
	/**
	 * 组件属性json
	 */
	@JBoltField(name="openOption" ,columnName="open_option",type="String", remark="组件属性json")
	public java.lang.String getOpenOption() {
		return getStr("open_option");
	}

}
