package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 微信关键词回复中的关键词定义
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatKeywords<M extends BaseWechatKeywords<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	@JBoltField(name="mpId" ,columnName="mp_id",type="Integer", remark="微信 ID")
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	@JBoltField(name="name" ,columnName="name",type="String", remark="NAME")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 模糊 全匹配
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 模糊 全匹配
	 */
	@JBoltField(name="type" ,columnName="type",type="Integer", remark="模糊 全匹配")
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 回复规则ID
	 */
	public M setAutoReplyId(java.lang.Integer autoReplyId) {
		set("auto_reply_id", autoReplyId);
		return (M)this;
	}
	
	/**
	 * 回复规则ID
	 */
	@JBoltField(name="autoReplyId" ,columnName="auto_reply_id",type="Integer", remark="回复规则ID")
	public java.lang.Integer getAutoReplyId() {
		return getInt("auto_reply_id");
	}

}
