package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 订单物流信息
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderShipping<M extends BaseOrderShipping<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单ID
	 */
	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	/**
	 * 订单ID
	 */
	@JBoltField(name="orderId" ,columnName="order_id",type="Integer", remark="订单ID")
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 收件人姓名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 收件人姓名
	 */
	@JBoltField(name="name" ,columnName="name",type="String", remark="收件人姓名")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 收件人固话
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 收件人固话
	 */
	@JBoltField(name="phone" ,columnName="phone",type="String", remark="收件人固话")
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 移动电话
	 */
	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	/**
	 * 移动电话
	 */
	@JBoltField(name="mobile" ,columnName="mobile",type="String", remark="移动电话")
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 买方昵称
	 */
	public M setBuyerNickname(java.lang.String buyerNickname) {
		set("buyer_nickname", buyerNickname);
		return (M)this;
	}
	
	/**
	 * 买方昵称
	 */
	@JBoltField(name="buyerNickname" ,columnName="buyer_nickname",type="String", remark="买方昵称")
	public java.lang.String getBuyerNickname() {
		return getStr("buyer_nickname");
	}

	/**
	 * 省份
	 */
	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	/**
	 * 省份
	 */
	@JBoltField(name="province" ,columnName="province",type="String", remark="省份")
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 城市
	 */
	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	/**
	 * 城市
	 */
	@JBoltField(name="city" ,columnName="city",type="String", remark="城市")
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 区县
	 */
	public M setCounty(java.lang.String county) {
		set("county", county);
		return (M)this;
	}
	
	/**
	 * 区县
	 */
	@JBoltField(name="county" ,columnName="county",type="String", remark="区县")
	public java.lang.String getCounty() {
		return getStr("county");
	}

	/**
	 * 收件具体地址
	 */
	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	/**
	 * 收件具体地址
	 */
	@JBoltField(name="address" ,columnName="address",type="String", remark="收件具体地址")
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 邮政编码
	 */
	public M setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
		return (M)this;
	}
	
	/**
	 * 邮政编码
	 */
	@JBoltField(name="zipcode" ,columnName="zipcode",type="String", remark="邮政编码")
	public java.lang.String getZipcode() {
		return getStr("zipcode");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	@JBoltField(name="updateTime" ,columnName="update_time",type="Date", remark="更新时间")
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 更新人ID
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新人ID
	 */
	@JBoltField(name="updateUserId" ,columnName="update_user_id",type="Integer", remark="更新人ID")
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	/**
	 * 订单编号
	 */
	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	/**
	 * 订单编号
	 */
	@JBoltField(name="orderNo" ,columnName="order_no",type="String", remark="订单编号")
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 买方用户ID
	 */
	public M setBuyerId(java.lang.Integer buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}
	
	/**
	 * 买方用户ID
	 */
	@JBoltField(name="buyerId" ,columnName="buyer_id",type="Integer", remark="买方用户ID")
	public java.lang.Integer getBuyerId() {
		return getInt("buyer_id");
	}

}
