package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 货架元素_商品组
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShelfGoodsGroup<M extends BaseShelfGoodsGroup<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	@JBoltField(name="name" ,columnName="name",type="String", remark="NAME")
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 图标
	 */
	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	/**
	 * 图标
	 */
	@JBoltField(name="icon" ,columnName="icon",type="String", remark="图标")
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 分类下的顶部修饰图
	 */
	public M setImgurl(java.lang.String imgurl) {
		set("imgurl", imgurl);
		return (M)this;
	}
	
	/**
	 * 分类下的顶部修饰图
	 */
	@JBoltField(name="imgurl" ,columnName="imgurl",type="String", remark="分类下的顶部修饰图")
	public java.lang.String getImgurl() {
		return getStr("imgurl");
	}

	/**
	 * 二级标题
	 */
	public M setSubTitle(java.lang.String subTitle) {
		set("sub_title", subTitle);
		return (M)this;
	}
	
	/**
	 * 二级标题
	 */
	@JBoltField(name="subTitle" ,columnName="sub_title",type="String", remark="二级标题")
	public java.lang.String getSubTitle() {
		return getStr("sub_title");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	@JBoltField(name="sortRank" ,columnName="sort_rank",type="Integer", remark="排序")
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 货架ID
	 */
	public M setShelfId(java.lang.Integer shelfId) {
		set("shelf_id", shelfId);
		return (M)this;
	}
	
	/**
	 * 货架ID
	 */
	@JBoltField(name="shelfId" ,columnName="shelf_id",type="Integer", remark="货架ID")
	public java.lang.Integer getShelfId() {
		return getInt("shelf_id");
	}

	/**
	 * 货架元素ID
	 */
	public M setShelfElementId(java.lang.Integer shelfElementId) {
		set("shelf_element_id", shelfElementId);
		return (M)this;
	}
	
	/**
	 * 货架元素ID
	 */
	@JBoltField(name="shelfElementId" ,columnName="shelf_element_id",type="Integer", remark="货架元素ID")
	public java.lang.Integer getShelfElementId() {
		return getInt("shelf_element_id");
	}

}
