package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;
import cn.jbolt.common.gen.JBoltField;

/**
 * 异地登录日志记录
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRemoteLoginLog<M extends BaseRemoteLoginLog<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	@JBoltField(name="id" ,columnName="id",type="Integer", remark="主键ID")
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 最近一次登录省份
	 */
	public M setLastLoginProvince(java.lang.String lastLoginProvince) {
		set("last_login_province", lastLoginProvince);
		return (M)this;
	}
	
	/**
	 * 最近一次登录省份
	 */
	@JBoltField(name="lastLoginProvince" ,columnName="last_login_province",type="String", remark="最近一次登录省份")
	public java.lang.String getLastLoginProvince() {
		return getStr("last_login_province");
	}

	/**
	 * 最近一次登录城市
	 */
	public M setLastLoginCity(java.lang.String lastLoginCity) {
		set("last_login_city", lastLoginCity);
		return (M)this;
	}
	
	/**
	 * 最近一次登录城市
	 */
	@JBoltField(name="lastLoginCity" ,columnName="last_login_city",type="String", remark="最近一次登录城市")
	public java.lang.String getLastLoginCity() {
		return getStr("last_login_city");
	}

	/**
	 * 最近一次登录时间
	 */
	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}
	
	/**
	 * 最近一次登录时间
	 */
	@JBoltField(name="lastLoginTime" ,columnName="last_login_time",type="Date", remark="最近一次登录时间")
	public java.util.Date getLastLoginTime() {
		return getDate("last_login_time");
	}

	/**
	 * 新登录省份
	 */
	public M setLoginProvince(java.lang.String loginProvince) {
		set("login_province", loginProvince);
		return (M)this;
	}
	
	/**
	 * 新登录省份
	 */
	@JBoltField(name="loginProvince" ,columnName="login_province",type="String", remark="新登录省份")
	public java.lang.String getLoginProvince() {
		return getStr("login_province");
	}

	/**
	 * 新登录城市
	 */
	public M setLoginCity(java.lang.String loginCity) {
		set("login_city", loginCity);
		return (M)this;
	}
	
	/**
	 * 新登录城市
	 */
	@JBoltField(name="loginCity" ,columnName="login_city",type="String", remark="新登录城市")
	public java.lang.String getLoginCity() {
		return getStr("login_city");
	}

	/**
	 * 新登录时间
	 */
	public M setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
		return (M)this;
	}
	
	/**
	 * 新登录时间
	 */
	@JBoltField(name="loginTime" ,columnName="login_time",type="Date", remark="新登录时间")
	public java.util.Date getLoginTime() {
		return getDate("login_time");
	}

	/**
	 * 登录用户ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 登录用户ID
	 */
	@JBoltField(name="userId" ,columnName="user_id",type="Integer", remark="登录用户ID")
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 登录用户名
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	/**
	 * 登录用户名
	 */
	@JBoltField(name="username" ,columnName="username",type="String", remark="登录用户名")
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 是否为最新一次
	 */
	public M setIsNew(java.lang.Boolean isNew) {
		set("is_new", isNew);
		return (M)this;
	}
	
	/**
	 * 是否为最新一次
	 */
	@JBoltField(name="isNew" ,columnName="is_new",type="Boolean", remark="是否为最新一次")
	public java.lang.Boolean getIsNew() {
		return getBoolean("is_new");
	}

	/**
	 * 最近一次登录IP
	 */
	public M setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
		return (M)this;
	}
	
	/**
	 * 最近一次登录IP
	 */
	@JBoltField(name="lastLoginIp" ,columnName="last_login_ip",type="String", remark="最近一次登录IP")
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}

	/**
	 * 新登录IP
	 */
	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}
	
	/**
	 * 新登录IP
	 */
	@JBoltField(name="loginIp" ,columnName="login_ip",type="String", remark="新登录IP")
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	/**
	 * 记录创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 记录创建时间
	 */
	@JBoltField(name="createTime" ,columnName="create_time",type="Date", remark="记录创建时间")
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

}
